spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: library
    password: library
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: LibraryManagementSystem
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: library
    password: library
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 6060

token:
  secret: 832t82eg8dgwd2fc8cg2bfg663fd6bftg8oe8g2e8hihrfghe87drf
  time: 30d